# Generated by Django 5.2.7 on 2025-11-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('tipo', models.CharField(choices=[('recordatorio_examen', 'Recordatorio de Examen'), ('recordatorio_clase', 'Recordatorio de Clase'), ('recordatorio_tarea', 'Recordatorio de Tarea'), ('aviso_general', 'Aviso General')], max_length=20)),
                ('fecha_programada', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.curso')),
            ],
        ),
    ]
