# Generated by Django 5.0 on 2025-11-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_mensajeprogramado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asistencia',
        ),
    ]
