# Generated by Django 5.2.8 on 2025-11-08 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_delete_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{15}$', 'El teléfono debe contener exactamente 15 números.')]),
        ),
    ]
