# Generated by Django 5.0 on 2025-11-10 17:34

import agency.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_alumno_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[agency.validators.validar_telefono_15_digitos]),
        ),
    ]
